channels:
- pytorch
- conda-forge
- defaults
dependencies:
- black=22.8.0
- ignite=0.4.10
- imageio=2.22.0
- openpyxl=3.0.10
- python-dotenv=0.21.0
- scikit-image=0.19.3
- scikit-learn=1.1.2
- tensorboard=2.10.0
- tqdm=4.64.1
- pip:
  - aiohttp==3.8.1
  - aiohttp-cors==0.7.0
  - aiorwlock==1.3.0
  - alabaster==0.7.12
  - alembic==1.8.1
  - antlr4-python3-runtime==4.9.3
  - anyio==3.6.1
  - argon2-cffi==21.3.0
  - argon2-cffi-bindings==21.2.0
  - asgiref==3.5.2
  - autopage==0.5.1
  - babel==2.10.3
  - beautifulsoup4==4.11.1
  - bleach==5.0.1
  - blessed==1.19.1
  - boto3==1.22.6
  - botocore==1.25.13
  - captum==0.5.0
  - click==8.0.4
  - cliff==4.0.0
  - cloudpickle==2.0.0
  - cmaes==0.8.2
  - cmd2==2.4.2
  - colorful==0.5.4
  - colorlog==6.7.0
  - data==0.4
  - defusedxml==0.7.1
  - distlib==0.3.6
  - docutils==0.19
  - easydict==1.9
  - fastapi==0.85.0
  - fastjsonschema==2.16.2
  - filelock==3.8.0
  - funcsigs==1.0.2
  - furo==2022.9.29
  - future==0.18.2
  - google-api-core==2.10.2
  - googleapis-common-protos==1.56.4
  - gpustat==1.0.0
  - greenlet==1.1.3
  - grpcio==1.43.0
  - h11==0.14.0
  - hydra-core==1.2.0
  - imagesize==1.4.1
  - iniconfig==1.1.1
  - ipykernel==6.17.0
  - ipython-genutils==0.2.0
  - ipywidgets==8.0.2
  - isort==5.10.1
  - jinja2==3.1.2
  - jmespath==1.0.1
  - jsonschema==4.16.0
  - jupyter==1.0.0
  - jupyter-console==6.4.4
  - jupyter-server==1.23.0
  - jupyterlab-pygments==0.2.2
  - jupyterlab-widgets==3.0.3
  - latex==0.7.0
  - mako==1.2.3
  - matplotlib==3.6.1
  - mistune==2.0.4
  - msgpack==1.0.4
  - nbclassic==0.4.8
  - nbclient==0.7.0
  - nbconvert==7.2.3
  - nbformat==5.7.0
  - notebook==6.5.2
  - notebook-shim==0.2.2
  - numpy==1.23.4
  - nvidia-cublas-cu11==11.10.3.66
  - nvidia-cuda-nvrtc-cu11==11.7.99
  - nvidia-cuda-runtime-cu11==11.7.99
  - nvidia-cudnn-cu11==8.5.0.96
  - nvidia-ml-py==11.495.46
  - omegaconf==2.2.3
  - opencensus==0.11.0
  - opencensus-context==0.1.3
  - optuna==3.0.3
  - pandas==1.5.1
  - pandocfilters==1.5.0
  - pbr==5.10.0
  - pickle5==0.0.11
  - plotly==5.10.0
  - pluggy==1.0.0
  - pockets==0.9.1
  - prettytable==3.4.1
  - prometheus-client==0.13.1
  - protobuf==3.19.6
  - py==1.11.0
  - py-spy==0.3.14
  - pyarrow==6.0.1
  - pydantic==1.10.2
  - pyimq==0.1
  - pyperclip==1.8.2
  - pyrsistent==0.18.1
  - pytest==7.1.3
  - python-graphviz==0.20.1
  - qtconsole==5.4.0
  - qtpy==2.3.0
  - s3transfer==0.5.2
  - scipy==1.8.1
  - send2trash==1.8.0
  - shutilwhich==1.1.0
  - smart-open==6.2.0
  - sniffio==1.3.0
  - snowballstemmer==2.2.0
  - soupsieve==2.3.2.post1
  - sphinx==5.3.0
  - sphinx-basic-ng==1.0.0b1
  - sphinxcontrib-applehelp==1.0.2
  - sphinxcontrib-devhelp==1.0.2
  - sphinxcontrib-htmlhelp==2.0.0
  - sphinxcontrib-jsmath==1.0.1
  - sphinxcontrib-napoleon==0.7
  - sphinxcontrib-qthelp==1.0.3
  - sphinxcontrib-serializinghtml==1.1.5
  - sqlalchemy==1.4.41
  - starlette==0.20.4
  - stevedore==4.0.0
  - tabulate==0.9.0
  - tempdir==0.7.1
  - tenacity==8.1.0
  - tensorboardx==2.5.1
  - terminado==0.17.0
  - tinycss2==1.2.1
  - torch==1.13.0+cu116
  - torch-tb-profiler==0.4.0
  - torchaudio==0.13.0+cu116
  - torchvision==0.14.0+cu116
  - torchviz==0.0.2
  - uvicorn==0.16.0
  - virtualenv==20.16.5
  - webencodings==0.5.1
  - websocket-client==1.4.2
  - widgetsnbextension==4.0.3