name: skinstression
channels:
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - libexpat=2.5.0
  - libffi=3.4.2
  - libsqlite=3.44.2
  - libzlib=1.2.13
  - openssl=3.2.0
  - pip=23.3.1
  - python=3.11.7
  - setuptools=68.2.2
  - tk=8.6.13
  - wheel=0.42.0
  - xz=5.2.6
  - pip:
      - absl-py==2.0.0
      - aiohttp==3.9.1
      - aiohttp-retry==2.8.3
      - aiosignal==1.3.1
      - amqp==5.2.0
      - annotated-types==0.6.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - asttokens==2.4.1
      - asyncssh==2.14.1
      - atpublic==4.0
      - attrs==23.1.0
      - billiard==4.2.0
      - cachetools==5.3.2
      - celery==5.3.6
      - certifi==2022.12.7
      - cffi==1.16.0
      - charset-normalizer==2.1.1
      - click==8.1.7
      - click-didyoumean==0.3.0
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - colorama==0.4.6
      - comm==0.2.0
      - configobj==5.0.8
      - contourpy==1.2.0
      - cryptography==41.0.7
      - cycler==0.12.1
      - debugpy==1.8.0
      - decorator==5.1.1
      - dictdiffer==0.9.0
      - diskcache==5.6.3
      - distro==1.8.0
      - dpath==2.1.6
      - dulwich==0.21.7
      - dvc==3.33.4
      - dvc-data==2.24.0
      - dvc-http==2.32.0
      - dvc-objects==2.0.1
      - dvc-render==1.0.0
      - dvc-studio-client==0.18.0
      - dvc-task==0.3.0
      - entrypoints==0.4
      - executing==2.0.1
      - filelock==3.9.0
      - flatten-dict==0.4.2
      - flufl-lock==7.1.1
      - fonttools==4.46.0
      - frozenlist==1.4.1
      - fsspec==2023.4.0
      - funcy==2.0
      - gitdb==4.0.11
      - gitpython==3.1.40
      - google-auth==2.25.2
      - google-auth-oauthlib==1.2.0
      - grandalf==0.8
      - grpcio==1.60.0
      - gto==1.6.1
      - h5py==3.10.0
      - h5torch==0.2.8
      - hydra-core==1.3.2
      - idna==3.4
      - ipykernel==6.27.1
      - ipython==8.18.1
      - iterative-telemetry==0.0.8
      - jedi==0.19.1
      - jinja2==3.1.2
      - joblib==1.3.2
      - jupyter-client==8.6.0
      - jupyter-core==5.5.0
      - kiwisolver==1.4.5
      - kombu==5.3.4
      - lightning==2.1.2
      - lightning-utilities==0.10.0
      - markdown==3.5.1
      - markdown-it-py==3.0.0
      - markupsafe==2.1.3
      - matplotlib==3.8.2
      - matplotlib-inline==0.1.6
      - mdurl==0.1.2
      - monai==1.3.0
      - mpmath==1.2.1
      - multidict==6.0.4
      - nest-asyncio==1.5.8
      - networkx==3.0rc1
      - numpy==1.26.2
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - opencv-python==4.8.1.78
      - orjson==3.9.10
      - packaging==23.2
      - pandas==2.1.4
      - parso==0.8.3
      - pathspec==0.12.1
      - pillow==9.3.0
      - platformdirs==3.11.0
      - prompt-toolkit==3.0.43
      - protobuf==4.23.4
      - psutil==5.9.6
      - pure-eval==0.2.2
      - pyasn1==0.5.1
      - pyasn1-modules==0.3.0
      - pycparser==2.21
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - pydot==1.4.2
      - pygit2==1.13.3
      - pygments==2.17.2
      - pygtrie==2.5.0
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - pytorch-lightning==2.1.2
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - requests==2.28.1
      - requests-oauthlib==1.3.1
      - rich==13.7.0
      - rsa==4.9
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - scmrepo==1.6.0
      - semver==3.0.2
      - shortuuid==1.0.11
      - shtab==1.6.5
      - six==1.16.0
      - smmap==5.0.1
      - sqltrie==0.10.0
      - stack-data==0.6.3
      - sympy==1.11.1
      - tabulate==0.9.0
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.2.0
      - tomlkit==0.12.3
      - torch==2.3.0
      - torchaudio==2.2.0
      - torchmetrics==1.2.1
      - torchvision==0.18.0
      - tornado==6.4
      - tqdm==4.66.1
      - traitlets==5.14.0
      - typer==0.9.0
      - typing-extensions==4.8.0
      - tzdata==2023.3
      - urllib3==1.26.13
      - vine==5.1.0
      - voluptuous==0.14.1
      - wcwidth==0.2.12
      - werkzeug==3.0.1
      - yarl==1.9.4
      - zc-lockfile==3.0.post1
