name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9.13
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.13
      - name: Install dependencies
        run: |
          $CONDA/bin/conda env update --file environment.yml --name base

      - name: Make HTML docs
        run: cd docs && make html

      - name: Deploy docs
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/build/html